# Generated by Django 2.2.4 on 2019-08-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_id', models.IntegerField(default=0)),
                ('town', models.CharField(max_length=256)),
                ('street', models.CharField(max_length=256)),
                ('building', models.CharField(max_length=256)),
                ('apartment', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('birth_date', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=256)),
                ('relatives', models.ManyToManyField(related_name='_citizen_relatives_+', to='shop.Citizen')),
            ],
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizens', models.ManyToManyField(to='shop.Citizen')),
            ],
        ),
    ]
